### ISSUE TITLE
Bug: remove backslash escaping in folder paths

### ISSUE THREAD

**Issue by bigdogdylan00** [LAB02-Research/HASS.Agent.AutoImport#1]
Hey there, this is my first time submitting an issue on Github so I apologize if the format isn't quite right. I created a custom folder on my desktop for Steam shortcuts, however when I pasted it in verbatim the program read the backslash as the beginning to an escape sequence. I was able to fix it by using double backslashes, as one would expect, however I'm not sure if there's an easy way to sanitize that input to correct that automatically.

**Comment by LAB02-Admin** [comment]
Yep you're right, glad you figured it out for yourself. I'll fix its behavior.

**Comment by LAB02-Admin** [comment]
Fixed in [2022.2.0](https://github.com/LAB02-Research/HASS.Agent.AutoImport/releases/tag/2022.2.0).

You'll need to one-time replace all double backslashes with singles in both appsettings.json and processedshortcuts.json.
